@startuml

<style>
root {
  BackgroundColor #4a556822 
  FontColor #718096
  LineColor #718096
  Margin 30
  Padding 10
}

stateDiagram {
  state {
    BackgroundColor #edf2f7
    LineColor #4a5568
    FontColor #2d3748
    RoundCorner 10
  }
  arrow {
    LineColor #718096
    FontColor #718096
  }
}
</style>


title Pixel - UML State Machine

[*] --> WaitInON : Pixel() (constructor)
WaitInON : entry /\n  pixelState = 9\n  display.set_pixel(x,y,pixelState)\n  myTimer.start()
WaitInON --> WaitInOFF : \n Timeout /
WaitInOFF: entry /\n  pixelState = 0\n  display.set_pixel(x,y,pixelState)\n  myTimer.start()
WaitInOFF --> WaitInON : \n Timeout /

@enduml